### ISSUE TITLE
Invalid project: Not working correctly

### ISSUE THREAD

**Issue by sm-tester** [dss886/Android-EmotionInputDetector#1]
Hi, your project now works right. Have you ever started this project?
![screenshot 1](https://cloud.githubusercontent.com/assets/3168694/10334680/31f3d2b8-6d05-11e5-950c-d6e8730e6b1b.jpg)

**Comment by dss886** [comment]
Sorry for upload a undone project, i am still woring on it...

**Comment by dss886** [comment]
Now the library should work properly.

**Comment by boyfox** [comment]
Ooo, Thanks @dss886 !!!

**Comment by sm-tester** [comment]
Hi dss886. This is your last 0.1.2 version, not works:

default screen:
![screenshot1](https://cloud.githubusercontent.com/assets/3168694/10534182/12483dec-73ee-11e5-9e5e-55afebe52582.jpg)

After clicking to input area:
![screenshot2](https://cloud.githubusercontent.com/assets/3168694/10534174/eb6b0664-73ed-11e5-9f01-6f9a1ca14d58.jpg)

my device nexus4

**Comment by dss886** [comment]
I may found where the problem is, there are some bugs getting the height of the soft button bar in different api versions.

please try again...

**Comment by sm-tester** [comment]
Hi dss886, not fixed, here your logs: 

10-19 10:33:28.154: D/SoftInputMethod(16534): 32
10-19 10:33:28.189: I/Keyboard.Facilitator(868): onFinishInput()

10-19 10:32:50.941: I/Keyboard.Facilitator(868): onStartInput()
10-19 10:32:50.951: I/LatinIME(868): Starting input. Cursor position = 0,0
10-19 10:32:50.987: I/Keyboard.Facilitator(868): resetDictionaries() : no-op
10-19 10:32:50.987: I/StatsUtilsManager(868): onLoadSettings()

**Comment by dss886** [comment]
I used a simulator to test Nexus4 at api level 16-22, then found something wrong within api 18-20 :(

Please try again, I think I have fixed it this time....

**Comment by sm-tester** [comment]
Hi @dss886 I tried test your project again, but still bug not fixed, please firstly do fix then say try.

**Comment by dss886** [comment]
Hi @boyfox , sorry for wasting your time, now I have no idea how did it happened, it seems work fine on my Nexus4 simulator at different api levels, I will keep an eye on it.

**Comment by sm-tester** [comment]
ok thanks!

**Comment by rongxianren** [comment]
if you set a background in the main layout,when then soft keyboard showup the background will be stretched.  what can l do to solve this problem.

**Comment by dss886** [comment]
@rongxianren please open a new issue and post your xml layout and java code

https://github.com/dss886/Android-EmotionInputDetector/issues/new
